# Generated by Django 6.1.1 on 2026-09-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('earthquake', 'Earthquake'), ('cyclone', 'Cyclone'), ('wildfire', 'Wildfire'), ('landslide', 'Landslide'), ('drought', 'Drought'), ('tsunami', 'Tsunami'), ('heatwave', 'Heatwave'), ('industrial', 'Industrial Accident'), ('other', 'Other')], max_length=30)),
                ('disaster_subtype', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('verified', 'Verified'), ('active', 'Active'), ('responding', 'Responding'), ('controlled', 'Controlled'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('alert_level', models.CharField(choices=[('green', 'Green'), ('orange', 'Orange'), ('red', 'Red')], default='orange', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('affected_area_km2', models.FloatField(blank=True, null=True)),
                ('affected_population', models.IntegerField(default=0)),
                ('injured_count', models.IntegerField(default=0)),
                ('missing_count', models.IntegerField(default=0)),
                ('death_count', models.IntegerField(default=0)),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('priority_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('incident_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='accounts.agency')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='incident_updates/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField()),
                ('people_trapped', models.IntegerField(default=0)),
                ('severity', models.IntegerField(choices=[(1, 'Minor'), (2, 'Moderate'), (3, 'Serious'), (4, 'Critical'), (5, 'Life-Threatening')], default=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sos_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='sos_videos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('ai_classification', models.JSONField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_reference', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_reports', to='incidents.incident')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
